### ISSUE TITLE
SonyLiv Stopped Working

### ISSUE THREAD

**Issue by devidasjadhav** [Vikassm73/AjaykRepo#138]
Great work on this project.

I have used SonyLiv plugin earlier and it was working without needing Any login to stream old episodes.
But now It seems I am not able to stream same.

using kodi version - 19.4
app version            - 2.0.15
Host OS                  - windows 10

error from kodi log
```
2023-01-02 17:15:47.014 T:22948   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'contactMessage'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\RandomUser\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 1116, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\RandomUser\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 1104, in router
                                                       play_video(params["video"], params["ltype"])
                                                     File "C:\Users\RandomUser\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 1007, in play_video
                                                       contactID = GETPROFILE()
                                                     File "C:\Users\RandomUser\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 113, in GETPROFILE
                                                       contactID = data['resultObj']['contactMessage'][0].get('contactID')
                                                   KeyError: 'contactMessage'
                                                   -->End of Python script error report<--
                                                   
2023-01-02 17:15:47.099 T:22948    INFO <general>: Python interpreter stopped
2023-01-02 17:15:47.112 T:17264   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.sonyliv/?action=Play&video=1000192609&ltype=Stream]

```

**Comment by Vikassm73** [comment]
Yes, it used to work without logins, but now even non-premium users must enter the mobile number.

**Comment by devidasjadhav** [comment]
Thanks, Its working with registered non premium member.
