### ISSUE TITLE
Zee5 and MXplayer is not installing. Kindly look into the issue.

### ISSUE THREAD

**Issue by prtkvashishth** [Vikassm73/AjaykRepo#18]

**Comment by Vikassm73** [comment]
Please let me know what error you are getting

**Comment by prtkvashishth** [comment]
Hii thanks for your quick revert. 

Sony liv is working very fine. Thanks for your efforts. Further, MX player and zee5 has installed but MX player is not opening by providing the error of MX Player error. ZEE5 - It has installed by resetting the Kodi app but live channels are not working. It's asking for premium subscription as well as also popping up the playback error. Kindly look into the issue.

**Comment by prtkvashishth** [comment]
![Uploading Screenshot_20210802-110028_Kodi.jpg…]()

**Comment by Vikassm73** [comment]
Zee5 is like a simple android app, no hacking. so If you have a valid logins, those premium live content will work. No problem in Mxplayer also. Your screenshot is not visible please resend it again.

**Comment by prtkvashishth** [comment]
Thanks for the update!! Zee5 is fine so I'll use the credentials. 

Refer screenshot for MX Player
![Screenshot_20210802-143758_Kodi](https://user-images.githubusercontent.com/82662354/127835743-fceb179e-4b86-49af-bbc2-cd78014b8796.jpg)

**Comment by Vikassm73** [comment]
Try to reinstall Mx player. 

Web series not added in Sonyliv as it is for premium user while we not added login feature in the Sonyliv.

**Comment by SSoft7** [comment]
@Vikassm73  This is the error for mxplayer

```
2021-08-02 20:47:23.858 T:18704    INFO <general>: initializing python engine.
2021-08-02 20:47:23.917 T:18704   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TabError'>
                                                   Error Contents: inconsistent use of tabs and spaces in indentation (plugin.py, line 557)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.MXPlayer\main.py", line 3, in <module>
                                                       from resources.lib import plugin
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.MXPlayer\resources\lib\plugin.py", line 557
                                                       poster=cover_image if cover_image else list_image
                                                                                                       ^
                                                   TabError: inconsistent use of tabs and spaces in indentation
                                                   -->End of Python script error report<--
                                                   
2021-08-02 20:47:23.933 T:18704    INFO <general>: Python interpreter stopped
2021-08-02 20:47:23.940 T:13152   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.MXPlayer/
2021-08-02 20:47:23.940 T:19308   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.MXPlayer/) failed
```

**Comment by Vikassm73** [comment]
uploaded again. Please check.

**Comment by SSoft7** [comment]
> uploaded again. Please check.

Is there any specific way to update the plugin? Just to make sure I am not using the old plugin, I have uninstalled the old and directly installed this zip file - https://github.com/Vikassm73/AjaykRepo/blob/main/Zips/plugin.video.MXPlayer/plugin.video.MXPlayer-1.0.5.zip

and the issue persists.

Another issue for sony liv, only when i click SonyLiv --> LiveTV --> "Live TV Channels" right after the "Live Sports Channel"
```
2021-08-02 21:10:51.162 T:4640     INFO <general>: initializing python engine.
2021-08-02 21:11:37.534 T:4640    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 633, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 613, in router
                                                       list_shows(params['cid'])
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 445, in list_shows
                                                       shows = cache.cacheFunction(get_shows,cid)
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\script.common.plugin.cache\resources\lib\storage_server\StorageServer.py", line 628, in cacheFunction
                                                       ret_val = funct(*args)
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.sonyliv\main.py", line 153, in get_shows
                                                       jd = requests.get(url,headers=headers).json()
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 900, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2021-08-02 21:11:37.649 T:4640     INFO <general>: Python interpreter stopped
2021-08-02 21:11:37.654 T:4824    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sonyliv/?action=list_shows&cid=532_552
2021-08-02 21:11:37.655 T:19308   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sonyliv/?action=list_shows&cid=532_552) failed
```

**Comment by Vikassm73** [comment]
You can update using Repo or download zip file in the local drive and update using zip option. 
Please again upload the Kodi log. 

Live TV Channels is not working in the Sonyliv.

**Comment by SSoft7** [comment]
> You can update using Repo or download zip file in the local drive and update using zip option.
> Please again upload the Kodi log.
> 
> Live TV Channels is not working in the Sonyliv.

I have already Updated directly using zip using the link i have posted above and the log is apparently the same - 

```
2021-08-02 21:53:56.068 T:5596     INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.video.MXPlayer v1.0.5 installed
2021-08-02 21:53:58.726 T:16812    INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2021-08-02 21:53:58.778 T:9504     INFO <general>: initializing python engine.
2021-08-02 21:53:58.828 T:9504    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TabError'>
                                                   Error Contents: inconsistent use of tabs and spaces in indentation (plugin.py, line 556)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.MXPlayer\main.py", line 3, in <module>
                                                       from resources.lib import plugin
                                                     File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.MXPlayer\resources\lib\plugin.py", line 556
                                                       poster=cover_image if cover_image else list_image
                                                                                                       ^
                                                   TabError: inconsistent use of tabs and spaces in indentation
                                                   -->End of Python script error report<--
                                                   
2021-08-02 21:53:58.842 T:9504     INFO <general>: Python interpreter stopped
2021-08-02 21:53:58.860 T:10372   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.MXPlayer/
2021-08-02 21:53:58.861 T:16812   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.MXPlayer/) failed
```

Live TV is working in sonyliv if I choose other options like "Entertainment".

**Comment by Vikassm73** [comment]
You are facing Tab/Space issue in Mxplayer. Unfortunately, I am not facing this issue anywhere that why it becomes difficult to rectify. Again done few corrections. Lets hope that it will work this time.

**Comment by SSoft7** [comment]
@Vikassm73  working perfectly now. thanks.
maybe you want to check sonyliv issue also.. That seems like json decoding error only.
