### ISSUE TITLE
Zee5 LiveTV not playing

### ISSUE THREAD

**Issue by shri1990** [Vikassm73/AjaykRepo#48]
Hi,
I have logged in with my Zee5 subscription and trying to play LiveTV and other premium movies but it's not playing. 
Could you please help sort this issue?

Logs captured.
2021-12-23 10:11:58.777 T:23860 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-12-23 10:12:10.742 T:23860    INFO <general>: Skipped 1 duplicate messages..
2021-12-23 10:12:10.742 T:23860    INFO <general>: CPythonInvoker(17, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zee5/main.py): script successfully run
2021-12-23 10:12:11.082 T:23860    INFO <general>: Python interpreter stopped
2021-12-23 10:12:14.324 T:23872    INFO <general>: initializing python engine.
2021-12-23 10:12:14.535 T:23872 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-12-23 10:12:26.771 T:23872   ERROR <general>: Skipped 1 duplicate messages..
2021-12-23 10:12:26.770 T:23872   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'keyOsDetails'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zee5/main.py", line 8, in <module>
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zee5/resources/lib/plugin.py", line 1024, in run
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zee5/resources/lib/plugin.py", line 1006, in router
                                                       play_live(params['vid'])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zee5/resources/lib/plugin.py", line 936, in play_live
                                                       video_url=data['keyOsDetails']['video_token']
                                                   KeyError: 'keyOsDetails'
                                                   -->End of Python script error report<--
                                                   
2021-12-23 10:12:27.130 T:23872    INFO <general>: Python interpreter stopped
2021-12-23 10:12:27.143 T:22110   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.zee5/?action=play_live&vid=0-9-241]
2021-12-23 10:12:27.143 T:22110    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-12-23 10:12:36.529 T:22110    INFO <general>: CWinSystemAndroid::DestroyWindow

**Comment by shri1990** [comment]
@Vikassm73, can you check this issue?

**Comment by Vikassm73** [comment]
Unable to test as I don't have valid login with email and password.

**Comment by shri1990** [comment]
@Vikassm73, i can provide you the subscription.. share your email id or telegram id..

**Comment by Vikassm73** [comment]
vikassm73@gmail.com
