### ISSUE TITLE
Zee5 not working

### ISSUE THREAD

**Issue by AbhayF8** [Vikassm73/AjaykRepo#60]
Nothing is opening in Zee5 
Log

I have logged in with Mobile No. and Password

2022-03-16 17:29:32.456 T:5875    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'keyOsDetails'
                                                   Traceback (most recent call last):
                                                     File "/home/abhay/.kodi/addons/plugin.video.zee5/main.py", line 8, in <module>
                                                       plugin.run()
                                                     File "/home/abhay/.kodi/addons/plugin.video.zee5/resources/lib/plugin.py", line 1223, in run
                                                       router(sys.argv[2][1:])
                                                     File "/home/abhay/.kodi/addons/plugin.video.zee5/resources/lib/plugin.py", line 1205, in router
                                                       playNew(params['vid'],params['itemtype'])
                                                     File "/home/abhay/.kodi/addons/plugin.video.zee5/resources/lib/plugin.py", line 999, in playNew
                                                       video_url=data['keyOsDetails'].get('hls_token')
                                                   KeyError: 'keyOsDetails'
                                                   -->End of Python script error report<--

**Comment by Vikassm73** [comment]
From setting, choose different device ID and try to play. Still does not work then can't do anything. I am not able to get device Id through any API.

**Comment by Vikassm73** [comment]
Check with new updates

**Comment by AbhayF8** [comment]
yes updated and now its working thanks
