### ISSUE TITLE
Voot Issue

### ISSUE THREAD

**Issue by SSoft7** [Vikassm73/AjaykRepo#77]
Hello,

I'm having issues with voot. The relevant error logs are following - 

```
2022-04-21 19:36:20.142 T:15660    INFO <general>: Creating InputStream
2022-04-21 19:36:20.144 T:15660    INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1057)
2022-04-21 19:36:20.264 T:7836     INFO <general>: Python interpreter stopped
2022-04-21 19:36:20.314 T:15660   ERROR <general>: CCurlFile::Open failed with code 404 for https://viacom-b.multitvsolution.com/viacomhls/rishteycineplex.m3u8:
                                                   <html>

2022-04-21 19:36:20.314 T:15660   ERROR <general>: AddOnLog: inputstream.adaptive: Download failed: https://viacom-b.multitvsolution.com/viacomhls/rishteycineplex.m3u8
2022-04-21 19:36:20.314 T:15660   ERROR <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://viacom-b.multitvsolution.com/viacomhls/rishteycineplex.m3u8)
```

Shemaroo

```
2022-04-21 19:40:38.945 T:1464     INFO <general>: Creating InputStream
2022-04-21 19:40:38.946 T:1464     INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1057)
2022-04-21 19:40:38.995 T:24300    INFO <general>: Python interpreter stopped
2022-04-21 19:40:39.035 T:1464    ERROR <general>: CCurlFile::FillBuffer - Failed: SSL connect error(35)
2022-04-21 19:40:39.035 T:1464    ERROR <general>: CCurlFile::Open failed with code 0 for https://voot.shemaroo.com/shemarootv/smil:shemarootvadp.smil/playlist.m3u8:

2022-04-21 19:40:39.035 T:1464    ERROR <general>: AddOnLog: inputstream.adaptive: Download failed: https://voot.shemaroo.com/shemarootv/smil:shemarootvadp.smil/playlist.m3u8
2022-04-21 19:40:39.035 T:1464    ERROR <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://voot.shemaroo.com/shemarootv/smil:shemarootvadp.smil/playlist.m3u8)
2022-04-21 19:40:39.035 T:1464    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.voot/?action=play&video=981709&quality=DASH_LINEAR_APP]
```

Other channels are giving "Premium Required". I already have premium and my logins are correct and working within the browser.

**Comment by Vikassm73** [comment]
Please check your problem get solved in new version or not. Unfortunately, I don't have valid logins to test.

**Comment by shri1990** [comment]
the premium episodes stopped working after this update, it was working untill yesterday..

**Comment by SSoft7** [comment]
Now this is the log

```
2022-04-29 23:16:22.543 T:1896     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.voot/?action=play&video=1301&vidtype=LIVE
2022-04-29 23:16:22.544 T:8520     INFO <general>: Creating InputStream
2022-04-29 23:16:22.545 T:8520     INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)
2022-04-29 23:16:22.596 T:208      INFO <general>: Python interpreter stopped
2022-04-29 23:16:23.113 T:8520     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 2, Type: live, Download speed: 0.0000 Bytes/s
2022-04-29 23:16:23.114 T:8520     INFO <general>: Creating Demuxer
2022-04-29 23:16:23.114 T:8520     INFO <general>: Opening stream: 1001 source: 256
2022-04-29 23:16:23.730 T:7160    ERROR <general>: CCurlFile::Open failed with code 403 for https://tv.media.jio.com/switch/bpk-tv/Colors_HD_voot_MOB/output03/hls/nw18aes.key-10261845c74a5642ba848d8e871d9748-1651254000.pkey:
                                                   <html>
                                                   
2022-04-29 23:16:23.730 T:7160    ERROR <general>: AddOnLog: inputstream.adaptive: Download failed: https://tv.media.jio.com/switch/bpk-tv/Colors_HD_voot_MOB/output03/hls/nw18aes.key-10261845c74a5642ba848d8e871d9748-1651254000.pkey
2022-04-29 23:16:23.735 T:8520  WARNING <general>: CVideoPlayer::OpenStream - Unsupported stream 1001. Stream disabled.
2022-04-29 23:16:23.735 T:8520     INFO <general>: Opening stream: 1002 source: 256
2022-04-29 23:16:23.736 T:8520     INFO <general>: Finding audio codec for: 86018
2022-04-29 23:16:23.736 T:8520     INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2022-04-29 23:16:23.736 T:8520     INFO <general>: Creating audio thread
2022-04-29 23:16:23.737 T:7612     INFO <general>: running thread: CVideoPlayerAudio::Process()
2022-04-29 23:16:23.737 T:8520     INFO <general>: CVideoPlayer::Process - eof reading from demuxer
2022-04-29 23:16:23.737 T:8520     INFO <general>: CVideoPlayer::OnExit()
2022-04-29 23:16:23.737 T:8520     INFO <general>: VideoPlayer: eof, waiting for queues to empty
2022-04-29 23:16:23.737 T:8520     INFO <general>: Closing stream player 1
2022-04-29 23:16:23.738 T:8520     INFO <general>: Waiting for audio thread to exit
2022-04-29 23:16:23.747 T:7612     INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2022-04-29 23:16:23.748 T:8520     INFO <general>: Closing audio device
2022-04-29 23:16:23.748 T:8520     INFO <general>: Deleting audio codec
2022-04-29 23:16:23.750 T:8520     INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2022-04-29 23:16:23.776 T:1896     INFO <general>: CVideoPlayer::CloseFile()
2022-04-29 23:16:23.778 T:1896     INFO <general>: VideoPlayer: waiting for threads to exit
2022-04-29 23:16:23.778 T:1896     INFO <general>: VideoPlayer: finished waiting
2022-04-29 23:16:23.778 T:1896     INFO <general>: CVideoPlayer::CloseFile()
2022-04-29 23:16:23.778 T:1896     INFO <general>: VideoPlayer: waiting for threads to exit
2022-04-29 23:16:23.778 T:1896     INFO <general>: VideoPlayer: finished waiting
```

**Comment by Vikassm73** [comment]
> 

Please send me a debug log. You can download and manually install a old version but you need to stop auto update addon

**Comment by Vikassm73** [comment]
> the premium episodes stopped working after this update, it was working untill yesterday..

Does live channels were working ?

**Comment by shri1990** [comment]
> > the premium episodes stopped working after this update, it was working untill yesterday..
> 
> Does premium live channels were working ?

There are only 11 channels listed in Live section and even they don't work..

**Comment by Vikassm73** [comment]
New version uploaded

**Comment by shri1990** [comment]
> New version uploaded

Live channels started working but premium and non-premium episodes are still not working..

**Comment by shri1990** [comment]
Also it would be good to have search option to search required program, movies etc..

**Comment by Vikassm73** [comment]
> > New version uploaded
> 
> Live channels started working but premium and non-premium episodes are still not working..

Send me a debug log

**Comment by shri1990** [comment]
> Send me a debug log. I don't have valid logins to test it.

2022-05-03 15:40:03.693 T:12926    INFO <general>: initializing python engine.
2022-05-03 15:40:05.218 T:12926    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.voot/default.py): script successfully run
2022-05-03 15:40:05.243 T:12691    INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.voot/?action=play&video=1309871&vidtype=VIDEO
2022-05-03 15:40:05.244 T:12930    INFO <general>: Creating InputStream
2022-05-03 15:40:05.250 T:12930    INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (2160 x 1080)
2022-05-03 15:40:05.345 T:12926    INFO <general>: Python interpreter stopped
2022-05-03 15:40:05.905 T:12930    INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 2, Type: live, Download speed: 0.0000 Bytes/s
2022-05-03 15:40:05.919 T:12930    INFO <general>: Creating Demuxer
2022-05-03 15:40:05.920 T:12930    INFO <general>: Opening stream: 1001 source: 256
2022-05-03 15:40:06.088 T:12930   FATAL <general>: AddOnLog: inputstream.adaptive: Unsupported encryption method: SAMPLE-AES
2022-05-03 15:40:06.089 T:12930 WARNING <general>: OpenStream - Unsupported stream 1001. Stream disabled.
2022-05-03 15:40:06.092 T:12930    INFO <general>: Opening stream: 1002 source: 256
2022-05-03 15:40:06.093 T:12930    INFO <general>: Finding audio codec for: 86018
2022-05-03 15:40:06.093 T:12930    INFO <general>: CDVDAudioCodecAndroidMediaCodec: extradata required for aac decoder!
2022-05-03 15:40:06.096 T:12930    INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2022-05-03 15:40:06.096 T:12930    INFO <general>: Creating audio thread
2022-05-03 15:40:06.096 T:12942    INFO <general>: running thread: CVideoPlayerAudio::Process()
2022-05-03 15:40:06.104 T:12930    INFO <general>: Process - eof reading from demuxer
2022-05-03 15:40:06.104 T:12930    INFO <general>: CVideoPlayer::OnExit()
2022-05-03 15:40:06.104 T:12930    INFO <general>: VideoPlayer: eof, waiting for queues to empty
2022-05-03 15:40:06.104 T:12930    INFO <general>: Closing stream player 1
2022-05-03 15:40:06.105 T:12930    INFO <general>: Waiting for audio thread to exit
2022-05-03 15:40:06.107 T:12942    INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2022-05-03 15:40:06.107 T:12930    INFO <general>: Closing audio device
2022-05-03 15:40:06.107 T:12930    INFO <general>: Deleting audio codec
2022-05-03 15:40:06.114 T:12930    INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2022-05-03 15:40:06.116 T:12691    INFO <general>: CVideoPlayer::CloseFile()
2022-05-03 15:40:06.117 T:12691    INFO <general>: VideoPlayer: waiting for threads to exit
2022-05-03 15:40:06.117 T:12691    INFO <general>: VideoPlayer: finished waiting
2022-05-03 15:40:06.117 T:12691    INFO <general>: CVideoPlayer::CloseFile()
2022-05-03 15:40:06.117 T:12691    INFO <general>: VideoPlayer: waiting for threads to exit
2022-05-03 15:40:06.117 T:12691    INFO <general>: VideoPlayer: finished waiting
2022-05-03 15:40:12.111 T:12961    INFO <general>: initializing python engine.
2022-05-03 15:40:13.483 T:12961    INFO <general>: CPythonInvoker(11, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.voot/default.py): script successfully run
2022-05-03 15:40:13.608 T:12961    INFO <general>: Python interpreter stopped
2022-05-03 15:40:14.507 T:12967    INFO <general>: initializing python engine.
2022-05-03 15:40:15.830 T:12967    INFO <general>: CPythonInvoker(12, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.voot/default.py): script successfully run
2022-05-03 15:40:15.959 T:12967    INFO <general>: Python interpreter stopped
2022-05-03 15:40:16.896 T:12971    INFO <general>: initializing python engine.
2022-05-03 15:40:18.438 T:12971    INFO <general>: CPythonInvoker(13, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.voot/default.py): script successfully run
2022-05-03 15:40:18.460 T:12691    INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.voot/?action=play&video=1309884&vidtype=VIDEO
2022-05-03 15:40:18.461 T:12975    INFO <general>: Creating InputStream
2022-05-03 15:40:18.468 T:12975    INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (2160 x 1080)
2022-05-03 15:40:18.566 T:12971    INFO <general>: Python interpreter stopped
2022-05-03 15:40:18.915 T:12975   FATAL <general>: AddOnLog: inputstream.adaptive: Unsupported encryption method: SAMPLE-AES
2022-05-03 15:40:18.916 T:12975   ERROR <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://cdnapisec.kaltura.com/p/1982551/sp/198255100/playManifest/protocol/https/entryId/1_1qspnk4h/format/applehttp/tags/tv/f/a.m3u8)
2022-05-03 15:40:18.916 T:12975   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.voot/?action=play&video=1309884&vidtype=VIDEO]
2022-05-03 15:40:18.916 T:12975    INFO <general>: CVideoPlayer::OnExit()
2022-05-03 15:40:18.918 T:12975    INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2022-05-03 15:40:18.937 T:12691    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-05-03 15:40:18.941 T:12691    INFO <general>: CVideoPlayer::CloseFile()

**Comment by Vikassm73** [comment]
Manually download old version 2.0.4 and check.

**Comment by shri1990** [comment]
> Manually download and install old version 2.0.4 and check.

As i mentioned earlier, its working in v2.0.4 but there is no Premium and Shows category available in the menu.. can you add those menu items over 2.0.4..

**Comment by Vikassm73** [comment]
For valid users, there is no changes in playing (For Premium as well as Non Premium content). If you delete login details, Non premium content will work fine.

Modifications are done in menu items and Live contents. and also for no login usage. Unfortunately, I can not test it properly without valid login details.

**Comment by SSoft7** [comment]
> This is not a debug log which I have expect.
> 
> follow #73
> 
> and upload using https://paste.kodi.tv
> 
> For valid users, there is no changes in playing (For Premium as well as Non Premium content). If you delete login details, Non premium content will work fine.
> 
> Modifications are done in menu items and Live contents. and also for no login usage. Unfortunately, I can not test it properly without valid login details.

Live TV is now working fine. I have tested premium episodes which does not seem to be working. I've only enabled curl debug log and you can find the log here -
https://paste.kodi.tv/apibixuyoc.kodi

Hopefully this log is enough, if you need a complete debug let me know.
Thanks.

**Comment by prakharaug** [comment]
Now free shows are not working

Logs
2022-05-04 14:32:02.252 T:18040   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Prakh\AppData\Roaming\Kodi\addons\plugin.video.voot\default.py", line 70, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\Prakh\AppData\Roaming\Kodi\addons\plugin.video.voot\default.py", line 62, in router
                                                       main.play(params['video'],params['vidtype'])
                                                     File "C:\Users\Prakh\AppData\Roaming\Kodi\addons\plugin.video.voot\resources\lib\main.py", line 768, in play
                                                       stream_url=jd['result'][0]['profileUrls'][0]['profileUrl']
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--

**Comment by Vikassm73** [comment]
For the time being, the Free show will work if the login details are removed. Premium episodes, I can't test fully without logins, so if I can't find a solution, I'll ignore it.

**Comment by SSoft7** [comment]
> For the time being, the Free show will work if the login details are removed. Premium episodes, I can't test fully without logins, so if I can't find a solution, I'll ignore it.

I can share logins. Let me know  your email.

**Comment by Vikassm73** [comment]
> > For the time being, the Free show will work if the login details are removed. Premium episodes, I can't test fully without logins, so if I can't find a solution, I'll ignore it.
> 
> I can share logins. Let me know your email.

vikassm73@gmail.com

**Comment by Vikassm73** [comment]
New Version uploaded

**Comment by shri1990** [comment]
> New Version uploaded. Please note that Premium content will not be available in HD. Also, If some times play back failed, try to play it again.

Everything is perfectly working for me now.. Thanks for your effort.. cheers

**Comment by SSoft7** [comment]
> New Version uploaded. Please note that Premium content will not be available in HD. Also, If some times play back failed, try to play it again.

Do you know why the premium content can't be played in HD?

Thank you for your efforts :-D

**Comment by Vikassm73** [comment]
It is issue of Inputstream Adaptive (Which help for playing content). If I select HD stream, it get freeze after 10 Sec.
